FROM sdhibit/rpi-raspbian

ENV INSTALL_TYPE stable
ENV BRANCHE_TYPE master

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y systemd && apt-get clean

ADD preinstall-armef.sh /tmp/preinstall-armef.sh

RUN chmod +x /tmp/preinstall-armef.sh
RUN /tmp/./preinstall-armef.sh && rm /tmp/preinstall-armef.sh && apt-get clean && apt-get autoclean

CMD ["/bin/systemd"]
